[package]
name = "where3"
version = "0.1.0"
authors = ["tobisakomd <tobisako@minden.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
